package Vue;

import Domaine.HeatMyFloorController;
import java.awt.Point;

public class MainWindowDesign extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindowDesign.class.getName());
    public HeatMyFloorController controller;
    //private final DrawingPanel drawingPanel;

    public MainWindowDesign() {
        controller = new HeatMyFloorController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBarFonctions = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mainPanel = new javax.swing.JPanel();
        buttonTopPanel = new javax.swing.JPanel();
        modelisationTypesBox = new javax.swing.JComboBox<>();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        ajoutMeubleButton = new javax.swing.JButton();
        meubleBox = new javax.swing.JComboBox<>();
        supprimerMeuble = new javax.swing.JButton();
        modifierMeuble = new javax.swing.JButton();
        InformationZoneBottomPanel = new javax.swing.JPanel();
        drawingCenterPanel = new javax.swing.JPanel();
        choixLeftPanel = new javax.swing.JPanel();
        longueurPieceJText = new javax.swing.JTextField();
        largeurPieceJText = new javax.swing.JTextField();
        longueurPieceJLabel = new javax.swing.JLabel();
        largeurPieceJLabel = new javax.swing.JLabel();
        titrePieceJLabel = new javax.swing.JLabel();
        nouvellePieceJButton = new javax.swing.JButton();
        typePieceJLabel = new javax.swing.JLabel();
        typePieceComboBox = new javax.swing.JComboBox<>();
        choixRightPanel = new javax.swing.JPanel();
        longeurJText = new javax.swing.JTextField();
        largeurJText = new javax.swing.JTextField();
        positionXJText = new javax.swing.JTextField();
        positionYJText = new javax.swing.JTextField();
        longueurJLabel = new javax.swing.JLabel();
        largeurJLabel = new javax.swing.JLabel();
        positionXJLabel = new javax.swing.JLabel();
        positionYJLabel = new javax.swing.JLabel();
        diametreJText = new javax.swing.JTextField();
        diametreJLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fichierMenu = new javax.swing.JMenu();
        nouvelleModelisationMenu = new javax.swing.JMenu();
        pieceReguliereItem = new javax.swing.JMenuItem();
        pieceIrreguliereItem = new javax.swing.JMenuItem();
        sauvegarderItem = new javax.swing.JMenuItem();
        exporterItem = new javax.swing.JMenuItem();
        importerItem = new javax.swing.JMenuItem();
        editionMenu = new javax.swing.JMenu();
        outilsMenu1 = new javax.swing.JMenu();
        aideMenu = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBarFonctions.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBarFonctions.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        buttonTopPanel.setPreferredSize(new java.awt.Dimension(1000, 50));

        modelisationTypesBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modélisation Pièce", "Modélisation Fil" }));
        modelisationTypesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelisationTypesBoxActionPerformed(evt);
            }
        });
        buttonTopPanel.add(modelisationTypesBox);

        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });
        buttonTopPanel.add(undoButton);

        redoButton.setText("Redo");
        buttonTopPanel.add(redoButton);

        ajoutMeubleButton.setText("Ajouter Meuble ");
        ajoutMeubleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutMeubleButtonActionPerformed(evt);
            }
        });
        buttonTopPanel.add(ajoutMeubleButton);

        meubleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ARMOIRE", "BAIN", "DOUCHE", "PLACARD", "TOILETTE", "VANITE" }));
        buttonTopPanel.add(meubleBox);

        supprimerMeuble.setText("Supprimer meuble");
        buttonTopPanel.add(supprimerMeuble);

        modifierMeuble.setText("Modifier meuble");
        buttonTopPanel.add(modifierMeuble);

        mainPanel.add(buttonTopPanel, java.awt.BorderLayout.PAGE_START);

        InformationZoneBottomPanel.setPreferredSize(new java.awt.Dimension(1000, 100));

        javax.swing.GroupLayout InformationZoneBottomPanelLayout = new javax.swing.GroupLayout(InformationZoneBottomPanel);
        InformationZoneBottomPanel.setLayout(InformationZoneBottomPanelLayout);
        InformationZoneBottomPanelLayout.setHorizontalGroup(
            InformationZoneBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        InformationZoneBottomPanelLayout.setVerticalGroup(
            InformationZoneBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mainPanel.add(InformationZoneBottomPanel, java.awt.BorderLayout.SOUTH);

        drawingCenterPanel.setPreferredSize(new java.awt.Dimension(250, 350));
        drawingCenterPanel.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                drawingCenterPanelMouseWheelMoved(evt);
            }
        });
        drawingCenterPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drawingCenterPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                drawingCenterPanelMouseEntered(evt);
            }
        });

        choixLeftPanel.setPreferredSize(new java.awt.Dimension(150, 350));

        longueurPieceJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longueurPieceJTextActionPerformed(evt);
            }
        });

        longueurPieceJLabel.setText("Longueur");

        largeurPieceJLabel.setText("Largeur");

        titrePieceJLabel.setText("Pièce ");

        nouvellePieceJButton.setText("Nouvelle piece");
        nouvellePieceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nouvellePieceJButtonActionPerformed(evt);
            }
        });

        typePieceJLabel.setText("Type");

        typePieceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regulière", "Irrégulière" }));
        typePieceComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typePieceComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choixLeftPanelLayout = new javax.swing.GroupLayout(choixLeftPanel);
        choixLeftPanel.setLayout(choixLeftPanelLayout);
        choixLeftPanelLayout.setHorizontalGroup(
            choixLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixLeftPanelLayout.createSequentialGroup()
                .addGroup(choixLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(choixLeftPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(choixLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(largeurPieceJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nouvellePieceJButton)
                            .addComponent(longueurPieceJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typePieceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typePieceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(longueurPieceJLabel)
                            .addComponent(largeurPieceJLabel)))
                    .addGroup(choixLeftPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(titrePieceJLabel)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        choixLeftPanelLayout.setVerticalGroup(
            choixLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixLeftPanelLayout.createSequentialGroup()
                .addComponent(titrePieceJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(typePieceJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typePieceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(longueurPieceJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(longueurPieceJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(largeurPieceJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(largeurPieceJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(nouvellePieceJButton)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        choixRightPanel.add(jMenuBarFonctions);

        javax.swing.GroupLayout drawingCenterPanelLayout = new javax.swing.GroupLayout(drawingCenterPanel);
        drawingCenterPanel.setLayout(drawingCenterPanelLayout);
        drawingCenterPanelLayout.setHorizontalGroup(
            drawingCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawingCenterPanelLayout.createSequentialGroup()
                .addContainerGap(694, Short.MAX_VALUE)
                .addComponent(choixLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        drawingCenterPanelLayout.setVerticalGroup(
            drawingCenterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawingCenterPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(choixLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainPanel.add(drawingCenterPanel, java.awt.BorderLayout.CENTER);

        choixRightPanel.setPreferredSize(new java.awt.Dimension(150, 350));

        longeurJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longeurJTextActionPerformed(evt);
            }
        });

        positionXJText.setPreferredSize(new java.awt.Dimension(100, 22));

        longueurJLabel.setText("Longueur");

        largeurJLabel.setText("Largeur");

        positionXJLabel.setText("Position X");

        positionYJLabel.setText("Position Y");

        diametreJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diametreJTextActionPerformed(evt);
            }
        });

        diametreJLabel.setText("Diamètre drain");

        javax.swing.GroupLayout choixRightPanelLayout = new javax.swing.GroupLayout(choixRightPanel);
        choixRightPanel.setLayout(choixRightPanelLayout);
        choixRightPanelLayout.setHorizontalGroup(
            choixRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixRightPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(choixRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(longueurJLabel)
                    .addComponent(diametreJLabel)
                    .addComponent(positionYJText)
                    .addComponent(positionXJLabel)
                    .addComponent(largeurJLabel)
                    .addComponent(positionXJText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(largeurJText)
                    .addComponent(longeurJText)
                    .addComponent(positionYJLabel)
                    .addComponent(diametreJText))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        choixRightPanelLayout.setVerticalGroup(
            choixRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choixRightPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(longueurJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(longeurJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(largeurJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(largeurJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(positionXJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionXJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(positionYJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionYJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(diametreJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diametreJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        choixRightPanel.add(jMenuBarFonctions);

        mainPanel.add(choixRightPanel, java.awt.BorderLayout.WEST);

        fichierMenu.setText("Fichier");

        nouvelleModelisationMenu.setText("Nouvelle modélisation");

        pieceReguliereItem.setText("Pièce regulière");
        nouvelleModelisationMenu.add(pieceReguliereItem);

        pieceIrreguliereItem.setText("Pièce irrégulière");
        nouvelleModelisationMenu.add(pieceIrreguliereItem);

        fichierMenu.add(nouvelleModelisationMenu);

        sauvegarderItem.setText("Sauvegarder");
        sauvegarderItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sauvegarderItemActionPerformed(evt);
            }
        });
        fichierMenu.add(sauvegarderItem);

        exporterItem.setText("Exporter");
        fichierMenu.add(exporterItem);

        importerItem.setText("Importer");
        fichierMenu.add(importerItem);

        mainMenuBar.add(fichierMenu);

        editionMenu.setText("Édition");
        mainMenuBar.add(editionMenu);

        outilsMenu1.setText("Outils");
        mainMenuBar.add(outilsMenu1);

        aideMenu.setText("Aide");
        mainMenuBar.add(aideMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1208, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sauvegarderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sauvegarderItemActionPerformed
        
    }//GEN-LAST:event_sauvegarderItemActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undoButtonActionPerformed

    private void modelisationTypesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelisationTypesBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelisationTypesBoxActionPerformed

    private void ajoutMeubleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutMeubleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutMeubleButtonActionPerformed

    private void longeurJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longeurJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longeurJTextActionPerformed

    private void drawingCenterPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawingCenterPanelMouseClicked
        // TODO : Test pour visualiser les positions x et y 
//        int h = drawingCenterPanel.getHeight();
//        int w = drawingCenterPanel.getWidth();
//        positionXJText.setText(Integer.toString(h));
//        positionYJText.setText(Integer.toString(w));
        
        Point p = evt.getPoint();
        
        positionXJText.setText(Integer.toString(p.x));
        positionYJText.setText(Integer.toString(p.y));
    }//GEN-LAST:event_drawingCenterPanelMouseClicked

    private void drawingCenterPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawingCenterPanelMouseEntered
        // TODO : Test pour visualiser la position des clics de souris
        Point p = evt.getPoint();
        positionXJText.setText(Integer.toString(p.x));
        positionYJText.setText(Integer.toString(p.y));
    }//GEN-LAST:event_drawingCenterPanelMouseEntered

    private void drawingCenterPanelMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_drawingCenterPanelMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_drawingCenterPanelMouseWheelMoved

    private void diametreJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diametreJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diametreJTextActionPerformed

    private void longueurPieceJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longueurPieceJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_longueurPieceJTextActionPerformed

    private void typePieceComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typePieceComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typePieceComboBoxActionPerformed

    private void nouvellePieceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouvellePieceJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nouvellePieceJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindowDesign().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InformationZoneBottomPanel;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JButton ajoutMeubleButton;
    private javax.swing.JPanel buttonTopPanel;
    private javax.swing.JPanel choixLeftPanel;
    private javax.swing.JPanel choixRightPanel;
    private javax.swing.JLabel diametreJLabel;
    private javax.swing.JTextField diametreJText;
    private javax.swing.JPanel drawingCenterPanel;
    private javax.swing.JMenu editionMenu;
    private javax.swing.JMenuItem exporterItem;
    private javax.swing.JMenu fichierMenu;
    private javax.swing.JMenuItem importerItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBarFonctions;
    private javax.swing.JLabel largeurJLabel;
    private javax.swing.JTextField largeurJText;
    private javax.swing.JLabel largeurPieceJLabel;
    private javax.swing.JTextField largeurPieceJText;
    private javax.swing.JTextField longeurJText;
    private javax.swing.JLabel longueurJLabel;
    private javax.swing.JLabel longueurPieceJLabel;
    private javax.swing.JTextField longueurPieceJText;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JComboBox<String> meubleBox;
    private javax.swing.JComboBox<String> modelisationTypesBox;
    private javax.swing.JButton modifierMeuble;
    private javax.swing.JMenu nouvelleModelisationMenu;
    private javax.swing.JButton nouvellePieceJButton;
    private javax.swing.JMenu outilsMenu1;
    private javax.swing.JMenuItem pieceIrreguliereItem;
    private javax.swing.JMenuItem pieceReguliereItem;
    private javax.swing.JLabel positionXJLabel;
    private javax.swing.JTextField positionXJText;
    private javax.swing.JLabel positionYJLabel;
    private javax.swing.JTextField positionYJText;
    private javax.swing.JButton redoButton;
    private javax.swing.JMenuItem sauvegarderItem;
    private javax.swing.JButton supprimerMeuble;
    private javax.swing.JLabel titrePieceJLabel;
    private javax.swing.JComboBox<String> typePieceComboBox;
    private javax.swing.JLabel typePieceJLabel;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
